module.exports = [
	{
		ignores: ["dist/**", "docs/**"],
	},
	{
		files: ["**/*.js"],
		languageOptions: {
			ecmaVersion: "latest",
			sourceType: "script",
			globals: {
				window: "readonly",
				document: "readonly",
				HTMLElement: "readonly",
				HTMLCanvasElement: "readonly",
				requestAnimationFrame: "readonly",
				cancelAnimationFrame: "readonly",
				SineWaveGenerator: "readonly",
				module: "readonly",
				require: "readonly",
				__dirname: "readonly",
				jest: "readonly",
				expect: "readonly",
				describe: "readonly",
				it: "readonly",
				beforeEach: "readonly",
				afterEach: "readonly",
				beforeAll: "readonly",
				afterAll: "readonly",
				process: "readonly",
				console: "readonly",
			},
		},
		rules: {
			"array-callback-return": "error",
			"consistent-return": "error",
			curly: ["error", "all"],
			"default-case": "error",
			eqeqeq: ["error", "always"],
			"no-alert": "error",
			"no-caller": "error",
			"no-constant-binary-expression": "error",
			"no-eval": "error",
			"no-extra-bind": "error",
			"no-floating-decimal": "error",
			"no-implied-eval": "error",
			"no-implicit-globals": "error",
			"no-iterator": "error",
			"no-labels": "error",
			"no-lone-blocks": "error",
			"no-loop-func": "error",
			"no-multi-assign": "error",
			"no-new-func": "error",
			"no-new-wrappers": "error",
			"no-param-reassign": ["error", { props: false }],
			"no-proto": "error",
			"no-return-assign": ["error", "always"],
			"no-shadow": "error",
			"no-throw-literal": "error",
			"no-undef-init": "error",
			"no-unneeded-ternary": "error",
			"no-unused-vars": [
				"error",
				{ argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
			],
			"no-useless-concat": "error",
			"no-useless-escape": "error",
			"no-var": "error",
			"object-shorthand": ["error", "always"],
			"prefer-const": "error",
			"prefer-template": "error",
		},
	},
];
